name: PR Checks

on:
  pull_request:
    branches:
      - development
      - testing
      - staging
      - main

jobs:
  lint:
    name: 🔍 Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.13.0
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run prettier:fix

      - name: Run Lint
        run: npm run lint:fix

  test:
    name: 🧪 Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22.13.0
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test

  all-checks-passed:
    needs: [lint, test]
    if: always()
    name: ✅ All Checks Passed
    runs-on: ubuntu-latest
    steps:
      - run: |
          FAILED=""
          # Проверяем каждый нужный джоб
          if [[ "${{ needs.lint.result }}" != "success" ]]; then
            FAILED+="lint "
          fi
          if [[ "${{ needs.test.result }}" != "success" ]]; then
            FAILED+="test "
          fi

          if [[ -n "$FAILED" ]]; then
            echo "The following required jobs failed or were skipped: $FAILED"
            exit 1
          fi
          echo "All required jobs passed!"
